name: "Debug workflow"
on: [push]

jobs:
  build:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: yarn install
      - run: yarn build
      - run: yarn test
